// ─── Crop Growth Tracking Service ──────────────────────────────────────────
// Tracks crop lifecycle stages, health, days elapsed, and problems detected

export const CROP_GROWTH_DATA = {
  Tomato: {
    crop: 'Tomato',
    emoji: '🍅',
    variety: 'Arka Rakshak (Hybrid)',
    field: 'Plot B — South Field',
    plantedDate: 'July 11, 2026',
    currentDay: 48,
    totalLifecycleDays: 90,
    currentStage: 'Flowering',
    currentStageIndex: 2,
    healthScore: 94,
    healthStatus: 'Excellent',
    detectedIssues: [],
    stages: [
      { id: 'germination', name: 'Germination', emoji: '🌱', startDay: 1, endDay: 10, status: 'completed', date: 'Jul 15' },
      { id: 'vegetative', name: 'Vegetative', emoji: '🌿', startDay: 11, endDay: 35, status: 'completed', date: 'Aug 5' },
      { id: 'flowering', name: 'Flowering', emoji: '🌼', startDay: 36, endDay: 60, status: 'current', date: 'Aug 28' },
      { id: 'fruiting', name: 'Fruiting', emoji: '🍅', startDay: 61, endDay: 80, status: 'upcoming', date: 'Sep 15' },
      { id: 'harvest', name: 'Harvest', emoji: '🌾', startDay: 81, endDay: 90, status: 'upcoming', date: 'Oct 01' },
    ],
    growthInsights: 'Flower retention is healthy (88% setting rate). Soil moisture at 32% requires vigilance to avoid flower drop before rain.',
  },
  Wheat: {
    crop: 'Wheat',
    emoji: '🌾',
    variety: 'HD-2967 (High Yield)',
    field: 'Plot A — North Field',
    plantedDate: 'June 15, 2026',
    currentDay: 74,
    totalLifecycleDays: 120,
    currentStage: 'Heading & Flowering',
    currentStageIndex: 3,
    healthScore: 91,
    healthStatus: 'Very Good',
    detectedIssues: [],
    stages: [
      { id: 'sowing', name: 'Sowing & Germination', emoji: '🌱', startDay: 1, endDay: 15, status: 'completed', date: 'Jun 25' },
      { id: 'tillering', name: 'Tillering', emoji: '🌿', startDay: 16, endDay: 40, status: 'completed', date: 'Jul 20' },
      { id: 'jointing', name: 'Jointing', emoji: '🎋', startDay: 41, endDay: 65, status: 'completed', date: 'Aug 10' },
      { id: 'heading', name: 'Heading & Flowering', emoji: '🌼', startDay: 66, endDay: 90, status: 'current', date: 'Aug 28' },
      { id: 'grain_fill', name: 'Grain Filling', emoji: '🌾', startDay: 91, endDay: 110, status: 'upcoming', date: 'Sep 20' },
      { id: 'harvest', name: 'Maturity & Harvest', emoji: '🚜', startDay: 111, endDay: 120, status: 'upcoming', date: 'Oct 10' },
    ],
    growthInsights: 'Ears have emerged with uniform density. Adequate moisture needed during pollen formation.',
  },
  Maize: {
    crop: 'Maize',
    emoji: '🌽',
    variety: 'Pioneer 3396',
    field: 'Plot C — East Field',
    plantedDate: 'July 01, 2026',
    currentDay: 58,
    totalLifecycleDays: 105,
    currentStage: 'Tasseling',
    currentStageIndex: 2,
    healthScore: 86,
    healthStatus: 'Good',
    detectedIssues: ['Minor leaf minor spots on outer border'],
    stages: [
      { id: 'emergence', name: 'Emergence', emoji: '🌱', startDay: 1, endDay: 12, status: 'completed', date: 'Jul 12' },
      { id: 'vegetative', name: 'Knee-High Vegetative', emoji: '🌿', startDay: 13, endDay: 45, status: 'completed', date: 'Aug 15' },
      { id: 'tasseling', name: 'Tasseling', emoji: '🌾', startDay: 46, endDay: 70, status: 'current', date: 'Aug 28' },
      { id: 'silking', name: 'Silking & Milking', emoji: '🌽', startDay: 71, endDay: 90, status: 'upcoming', date: 'Sep 18' },
      { id: 'harvest', name: 'Harvest', emoji: '🚜', startDay: 91, endDay: 105, status: 'upcoming', date: 'Oct 15' },
    ],
    growthInsights: 'Silks are receptive. Water stress at this juncture causes poor kernel pollination.',
  },
  Cotton: {
    crop: 'Cotton',
    emoji: '🪴',
    variety: 'Bt Cotton RCH-659',
    field: 'Plot D — West Field',
    plantedDate: 'May 20, 2026',
    currentDay: 100,
    totalLifecycleDays: 160,
    currentStage: 'Boll Development',
    currentStageIndex: 3,
    healthScore: 89,
    healthStatus: 'Very Good',
    detectedIssues: [],
    stages: [
      { id: 'seedling', name: 'Seedling', emoji: '🌱', startDay: 1, endDay: 20, status: 'completed', date: 'Jun 10' },
      { id: 'squaring', name: 'Squaring', emoji: '🌿', startDay: 21, endDay: 60, status: 'completed', date: 'Jul 20' },
      { id: 'flowering', name: 'Peak Flowering', emoji: '🌼', startDay: 61, endDay: 90, status: 'completed', date: 'Aug 18' },
      { id: 'boll_dev', name: 'Boll Development', emoji: '🪴', startDay: 91, endDay: 130, status: 'current', date: 'Aug 28' },
      { id: 'harvest', name: 'Boll Opening & Picking', emoji: '🚜', startDay: 131, endDay: 160, status: 'upcoming', date: 'Oct 25' },
    ],
    growthInsights: 'Boll retention is high. Maintain balanced potassium to optimize lint strength.',
  },
};

export const growthTrackingService = {
  getGrowthTracking(crop = 'Tomato') {
    return CROP_GROWTH_DATA[crop] || CROP_GROWTH_DATA.Tomato;
  },
};
